// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package if4031;

public interface gStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:if4031.gString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>optional string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
