// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package if4031;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:if4031.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string nickname = 1;</code>
   */
  java.lang.String getNickname();
  /**
   * <code>optional string nickname = 1;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>optional string channel = 2;</code>
   */
  java.lang.String getChannel();
  /**
   * <code>optional string channel = 2;</code>
   */
  com.google.protobuf.ByteString
      getChannelBytes();

  /**
   * <code>optional string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional string time = 4;</code>
   */
  java.lang.String getTime();
  /**
   * <code>optional string time = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
