// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package if4031;

/**
 * Protobuf type {@code if4031.paramSendTo}
 */
public  final class paramSendTo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:if4031.paramSendTo)
    paramSendToOrBuilder {
  // Use paramSendTo.newBuilder() to construct.
  private paramSendTo(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private paramSendTo() {
    param1_ = "";
    param2_ = "";
    param3_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private paramSendTo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();

            param1_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();

            param2_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();

            param3_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return if4031.Chat.internal_static_if4031_paramSendTo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return if4031.Chat.internal_static_if4031_paramSendTo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            if4031.paramSendTo.class, if4031.paramSendTo.Builder.class);
  }

  public static final int PARAM1_FIELD_NUMBER = 1;
  private volatile java.lang.Object param1_;
  /**
   * <code>optional string param1 = 1;</code>
   */
  public java.lang.String getParam1() {
    java.lang.Object ref = param1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        param1_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string param1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getParam1Bytes() {
    java.lang.Object ref = param1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      param1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAM2_FIELD_NUMBER = 2;
  private volatile java.lang.Object param2_;
  /**
   * <code>optional string param2 = 2;</code>
   */
  public java.lang.String getParam2() {
    java.lang.Object ref = param2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        param2_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string param2 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getParam2Bytes() {
    java.lang.Object ref = param2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      param2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAM3_FIELD_NUMBER = 3;
  private volatile java.lang.Object param3_;
  /**
   * <code>optional string param3 = 3;</code>
   */
  public java.lang.String getParam3() {
    java.lang.Object ref = param3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        param3_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string param3 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getParam3Bytes() {
    java.lang.Object ref = param3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      param3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getParam1Bytes().isEmpty()) {
      output.writeBytes(1, getParam1Bytes());
    }
    if (!getParam2Bytes().isEmpty()) {
      output.writeBytes(2, getParam2Bytes());
    }
    if (!getParam3Bytes().isEmpty()) {
      output.writeBytes(3, getParam3Bytes());
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!getParam1Bytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getParam1Bytes());
    }
    if (!getParam2Bytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getParam2Bytes());
    }
    if (!getParam3Bytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getParam3Bytes());
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static if4031.paramSendTo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static if4031.paramSendTo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static if4031.paramSendTo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static if4031.paramSendTo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static if4031.paramSendTo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static if4031.paramSendTo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static if4031.paramSendTo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static if4031.paramSendTo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static if4031.paramSendTo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static if4031.paramSendTo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(if4031.paramSendTo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code if4031.paramSendTo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:if4031.paramSendTo)
      if4031.paramSendToOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return if4031.Chat.internal_static_if4031_paramSendTo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return if4031.Chat.internal_static_if4031_paramSendTo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              if4031.paramSendTo.class, if4031.paramSendTo.Builder.class);
    }

    // Construct using if4031.paramSendTo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      param1_ = "";

      param2_ = "";

      param3_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return if4031.Chat.internal_static_if4031_paramSendTo_descriptor;
    }

    public if4031.paramSendTo getDefaultInstanceForType() {
      return if4031.paramSendTo.getDefaultInstance();
    }

    public if4031.paramSendTo build() {
      if4031.paramSendTo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public if4031.paramSendTo buildPartial() {
      if4031.paramSendTo result = new if4031.paramSendTo(this);
      result.param1_ = param1_;
      result.param2_ = param2_;
      result.param3_ = param3_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof if4031.paramSendTo) {
        return mergeFrom((if4031.paramSendTo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(if4031.paramSendTo other) {
      if (other == if4031.paramSendTo.getDefaultInstance()) return this;
      if (!other.getParam1().isEmpty()) {
        param1_ = other.param1_;
        onChanged();
      }
      if (!other.getParam2().isEmpty()) {
        param2_ = other.param2_;
        onChanged();
      }
      if (!other.getParam3().isEmpty()) {
        param3_ = other.param3_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if4031.paramSendTo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (if4031.paramSendTo) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object param1_ = "";
    /**
     * <code>optional string param1 = 1;</code>
     */
    public java.lang.String getParam1() {
      java.lang.Object ref = param1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param1_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string param1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getParam1Bytes() {
      java.lang.Object ref = param1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string param1 = 1;</code>
     */
    public Builder setParam1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      param1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string param1 = 1;</code>
     */
    public Builder clearParam1() {
      
      param1_ = getDefaultInstance().getParam1();
      onChanged();
      return this;
    }
    /**
     * <code>optional string param1 = 1;</code>
     */
    public Builder setParam1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      param1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object param2_ = "";
    /**
     * <code>optional string param2 = 2;</code>
     */
    public java.lang.String getParam2() {
      java.lang.Object ref = param2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param2_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string param2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParam2Bytes() {
      java.lang.Object ref = param2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string param2 = 2;</code>
     */
    public Builder setParam2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      param2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string param2 = 2;</code>
     */
    public Builder clearParam2() {
      
      param2_ = getDefaultInstance().getParam2();
      onChanged();
      return this;
    }
    /**
     * <code>optional string param2 = 2;</code>
     */
    public Builder setParam2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      param2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object param3_ = "";
    /**
     * <code>optional string param3 = 3;</code>
     */
    public java.lang.String getParam3() {
      java.lang.Object ref = param3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param3_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string param3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParam3Bytes() {
      java.lang.Object ref = param3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string param3 = 3;</code>
     */
    public Builder setParam3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      param3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string param3 = 3;</code>
     */
    public Builder clearParam3() {
      
      param3_ = getDefaultInstance().getParam3();
      onChanged();
      return this;
    }
    /**
     * <code>optional string param3 = 3;</code>
     */
    public Builder setParam3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      param3_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:if4031.paramSendTo)
  }

  // @@protoc_insertion_point(class_scope:if4031.paramSendTo)
  private static final if4031.paramSendTo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new if4031.paramSendTo();
  }

  public static if4031.paramSendTo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static final com.google.protobuf.Parser<paramSendTo> PARSER =
      new com.google.protobuf.AbstractParser<paramSendTo>() {
    public paramSendTo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new paramSendTo(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<paramSendTo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<paramSendTo> getParserForType() {
    return PARSER;
  }

  public if4031.paramSendTo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

